dist: trusty
sudo: required

branches:
  only:
    - master

env:
  global:
    # This environment variable tells Terraform not to prompt for input. This is
    # not required, but if we make a mistake, the Travis builder will hang waiting
    # for user input, tying up unnecessary resources.
    - TF_INPUT=false

    - GH_USERNAME="TravisCI"
    - GH_USER_EMAIL="ugo.enyioha@usableapps.io"
    - GH_REPO=ugoenyioha/azure-terraform-blueprints

#install terraform
before_install:
  - chmod +x scripts/install_terraform.sh
  - scripts/install_terraform.sh

script:
  - |
    cd stage/global/
    terraform init -backend-config="storage_account_name=STORAGE_ACCOUNT_NAME" \
                   -backend-config="container_name=CONTAINER_NAME"  \
                   -backend-config="key=stage.terraform.tfstate" \
                   -backend-config="resource_group_name=RESOURCE_GROUP_NAME" \
                   -backend-config="access_key=ACCESS_KEY"
    terraform plan

# terraform apply
deploy:
  - provider: script
    skip_cleanup: true
    script: "scripts/deploy.sh"
    on:
      repo:
      branch: master