dist: trusty
sudo: required
branches:
  only:
  - master
env:
  global:
  - TF_INPUT=false
  - GH_USERNAME="TravisCI"
  - GH_USER_EMAIL="ugo.enyioha@usableapps.io"
  - GH_REPO=ugoenyioha/azure-terraform-blueprints

  # azure
  - STORAGE_ACCOUNT_NAME=uapsterraformstorage
  - CONTAINER_NAME=ua-ps-terraform-container
  - STATE_KEY=stage.terraform.tfstate
  - RESOURCE_GROUP_NAME=uapetshopresourcegroup

  # azure STORAGE_ACCESS_KEY
  - secure: "fl4UQXWyEGsUoTGaWhv2X0Q58un3S+lZG5fAEvFIxtfSHtNVGYQHTaJEmRKTwm5zZTW08bZnBsPz3No8Js533MsSMMgTOSD+3RcGBKPooVc8047/7/gEkjSNLL+MYjUPuR2kLXCAqWDPMuT2SOg5wqy4dDW07e6zleqzrxrTToWSFnQEdUSIKc4KFOad1Ce61pjI2MszXmdpF57OcmKItPt2UWPLGMAsIPL8fvWjZxz1qoBu5W3Bf2/Sy+PGJRwuRwm7t8t4HE2lufQuvXl4Jh+1Gr3LVO4jRlaLu6LYT9rVzFnstGoe/yFAEQeDWzGLDbWYgetPfFKYYyc4A0uflyhYo/4jSgXdcpyQ8XI+WiPxjXV4YCCInOQpmVNtW9WzI1Mu65tj3U2bMFnw0928xK5oPQvBsuMcXOUcT/T8arLGFzykpNd1dJX44dBot9S1ddCqGsDnxcJS/63PzkMQuNSqsdga9kcQ8sx/xpkQctRA8K6znqZihQEC/lgih1lbG1qnaOrLBrN/sjaiBArbKs4TMUBhNxbcZobs1QuB/q25F9hbbln2bRY85kjgkaTy5eblc7EV1N2cIIozmx8ngJcZ2NQI/gmCSe+iS37VUU16RjhAa0LnQ1HZpCJQtpI1ITLOqZJ3sfjsOZ5ct2M8BYQSRvT+2gFHZfFMKnHAXrE="
  # AZURE_SUBSCRIPTION_ID
  - secure: "gf6F9BSpKgteRRd3AylAprGSpMEnTWV2TuTz/R0e4heM53nTra2I/ThwTnop+2cW/ubzRp4Nd/qg9+8WDJ0VjrglzrbRMmJESZOV6iXRr95yxkzrOaFUFTYFZmGrQT7kUDtoboYe7NazRKRrZEVHKU8+z8oA7fmrYeTon9mdNI9EsOrNwjqGJIrTRmWWPUQDF1iKqf6xyCxYNddfYkXOk94T/NyHZ2Wa3AuFOHonYp3ntZYEEX1fQjl71uABGvtuAm258sm3sNIYZfZr0L7c4MJ9uLZ7QcrG2O2rmfP027BXHa3a/A5wmEVjf1pfaJM26Bi6gdIqVMpledAvC9NynjgW3w6/jEUBpPw7t65fm6hDAmVFo4o44HVhIolSwaQc2GBI2MMNoIyEdoL9nj7Aaj+XP2qG6edbEwUXBOD1EBEVdA54I+S8aloWxVNrKEFwCaDjCm5en7a97u6//FizcUhNG5iVj8hrLxQ0gbAMQiKpSpKgLIdRhvW5LQn5qz+hDmyy6OKEMc6TLUtb5k3Nk9KKYsaeOyFL0C9Nle4m7YQyDFZqKZj1dV8jG0deJsVR2HYKBNa8xVEtGPfLWYF0Gl25mnO3Ma7b4rcTTZy5u9HR+ZAPrTdzNsB2rdK6xdCAMeGYQwnQmmQymrnLZTrxbYvYBlF2irMBluq7Sv//Nis="
  # AZURE_CLIENT_ID
  - secure: "u5mUDPSRade3J0YFTmPUiayWb985s4B3OqdQB0phcRKijhIH3956VcQWbCDxFvniM8bo4+ugXLIusjwt3LPUM91fyyVpb/Xj/I/L/EHRx9AKot4eDjnA1hOyX8MFr1Ka/pmIcx20LFM5eFSbS4JuPjMJwkQFw2c2fz4drorLNJ2uQ1tm0NesYtLuk0uUAKSZRfkHnTICaWHQkbwXYy0uZF11610waoAjK4YNMlULG+bosHjPH+5Ruxbpq+8Re7rf5pKcgNqQ4oEDO9ed8L8OU9/GiYf8whH/KL3q8vR2b9nqZ55bByApitKExXWl7ZUv9xG5iU+16yhbEUB2Q/Y5a01YqPQQdSuevRBPT7QYYr5AL7zeOtCXKgtgz39AJwncdt/zIbgWd6iu2w7dVoxBxGPwyPTGdRTxD0Q3alr4ETWvq17I0nadJVRt/TIlzZjDgf7brvJ9QcqqT84/tp3BjbIeUBgq8g8BnBBY5T6F/d2d9cayT8wfUZJxWCB7CHvsb3OA1S81H/rSDrdy0B4P5abRQU8s83pz/mYbn2EtdkPfVOQ4nkxTzQWbGsLjR2L/CW0BNlM3Mhv/09rBGB7SxnX4PYG65j2sWzz+b80lbCh9y7upFroYjBOIcSCJtWwKc8wT6rpACXoXLf8zeUEZuZevny1Wh1Fz7rgZvI1QWGY="
  # AZURE_CLIENT_SECRET
  - secure: "jDQp5Gd85NtX7vXsDnor/YQDofzYEQJH/YOWh/Hvg0iqrM0r1jSVpwCmkZyLOs0WpZGYEwj2poKPzSW9UVqOyPEcBxPcAGtwwWXwkNBmpEVshwQXzXDnFDIt40Mj/FQZduZYR2QtMCTKa/MqkRXlYBnAp5Mo5BUmds6/H5zHgAbXTP1aEgsOD8J9rbksOZQjHyTOM7WZLy54P8d7HuHIUQhNhktLLGB905DeWyIVlHLN7dUs7wKaVobRgK4oDDPY+9GdCNzOYdzFRSf8lmsZq6PLhtvoKxMtkYMIsiM3x0iCUM0VomX4CjLLZdhXYxNRKk7atxvEPy5KII1j7rR3AkCF/w0oC1oKC5q8E5T5W3vzSxloll/Vy32U88pTqjQ53lbtipaFrqqRzvtFBlDE4sGuAdHtugDsARlpwc2vaz1p93YPsc8oECJbf3I+pq8AwvNsYU+kJF/XLgu/TMAppOI59xU4rHa35bhKGHTtxc6QASagroHpHHlUexwvDI35zJmIR6lPOC5GpTn7MdylcgJsrROVQa29G0QV5BIJ7ZVL7+JAJ8WZmBHMvZbXy/8ucUKj8R7witF43GXNwlBjI+y1GKd8d2IVOz0gv7iYhsNUMsbx9igfB4E4MrFeOzbmOqKMqxMBqx+3K9ACHOcLHSJxWxRjB3po0UJmK5iWJyg="
  # AZURE_TENANT_ID
  - secure: "Og9zLaFIs25vaKB14caf9bnNQFRxCBPl7yHJcxTkZe8SL0V38V2svD9lYJyMQqZw3wqKM8dqrr/7G3pDpZJD33lqcmZuIojsyWdZJmsgLAbA//i9h4t5Ke4Fw4teDtnNO8qAUG+y0jbHMZ7y/921aB05VbR3WdysIVMKIYqaBJvlt7D5Mjs4QGulatrrUdmT6G544GQcIX8c400MEphkeOPI4S4h1pqXNWdQwzlBI+LSbQJeGsy6X0YelWtFJ1+d285N+XWBIid/Ga2Jn4QDEEuHfaU8XeDRCugOaxD1dj9aywI6RBjiywNjsmst5k5lR3/B7GelyPe/7TFUesi2nHbZ8OgUb2jVZ2Q1jyvFmbAHwBpaFUxF5caWhXopuwhnklQ779YwXyD44ssChwPgR4qx2lbPEfEZHNzZQx6fHPFc5UQmZBDClwXQVMOcyCcPO+SbacGBxWMEg5o+mIwXjehkGj9b12qaKs07/Y3T8X8JM4oVtqd1XKMfpDDBnu/7b/d8GbaBpVvwRqDVZGMiIdRRCzkAChuExakC8n5fOrpXHnSsilQdjKK8r4yOO9a1nFBHxHmuybFcHdYnACXMrgod80Dm9ozHNsGjLxzpXb7OSDVBH4mC+M7YWdEyEKbWQqXbM8FxTXLLyUaZ5r/tYt63YS/UlTuXogcJnrmkjWI="

  - TF_azure_subscription_id=${AZURE_SUBSCRIPTION_ID}
  - TF_azure_client_id=${AZURE_CLIENT_ID}
  - TF_azure_client_secret=${AZURE_CLIENT_SECRET}
  - TF_azure_tenant_id=${AZURE_TENANT_ID}

before_install:
- chmod +x scripts/install_terraform.sh
- scripts/install_terraform.sh
script:
- |
  cd stage/global/
  terraform init -backend-config="storage_account_name=${STORAGE_ACCOUNT_NAME}" \
                 -backend-config="container_name=${CONTAINER_NAME}"  \
                 -backend-config="key=${STATE_KEY}" \
                 -backend-config="resource_group_name=${RESOURCE_GROUP_NAME}" \
                 -backend-config="access_key=${STORAGE_ACCESS_KEY}"
  terraform plan
  
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    repo: 
    branch: master
