dist: trusty
sudo: required
branches:
  only:
  - master
env:
  global:
  - TF_INPUT=false
  - TF_IN_AUTOMATION=1
  - GH_USERNAME="TravisCI"
  - GH_USER_EMAIL="ugo.enyioha@usableapps.io"
  - GH_REPO=ugoenyioha/azure-terraform-blueprints

  # azure
  - AZURE_STORAGE_ACCOUNT_NAME=psterraformstorage
  - AZURE_CONTAINER_NAME=psterraformcontainer
  - AZURE_STAGE_GLOBAL_STATE_KEY=stage.global.terraform.tfstate
  - AZURE_STAGE_NETWORK_STATE_KEY=stage.network.terraform.tfstate
  - AZURE_STAGE_APPS_STATE_KEY=stage.apps.terraform.tfstate
  - AZURE_STAGE_REGISTRY_STATE_KEY=stage.registry.terraform.tfstate
  - AZURE_RESOURCE_GROUP_NAME=petshopresourcegroup

  # AZURE_STORAGE_ACCESS_KEY
  - secure: "wv8AaO9hpMDRgbMNQqCwGeyVOIhK/K3A76n1XIuIt/ksk7Cr3CD0v6SbdlKtaEwmss57CuhC6GoegmgHWI44qj6zP3lAG/VzCY6/stX+NN1TMmLyc1Ghs/FNjvJQJvmiy0et0bO/oeRAw82t/5xiOiMkPeILnY47c1Y4+HhuAW8NpiMXQM+sAIN4mLKcWdpIGNx/Uhf0hWRU0dtoQ8l0Gxxv1RkcSre7tWuUfvrz7og91QLLfYIlzmGssKuBIhj+4mj2SsayndyED8nj/meE1dYkQeMgXUZG6mOF/JoG0pjw+qP7ciaeyQqlHWr9LyrlFoMEOdWUjuV4r9dn15MVIG5zjPzLN2CuoyFAk8sfGWp+545adBJsnFa9dnW0VRmXgDbDPxNYWRUsbvOSDKjiEt/57gOom8I/HeAxExdg9qFAIOkFkkNKekPGAB4A1ITs8f9fy2mRuCy2CjxqRZekaEiE7dcX5p5NXcO50pFCsaW04olhGxvZVHbrcBQ+Ri4GT+1mMDsQ3/tDCAgwzK3YmIRn2Gd/weabhTR+7LKCSr6nyx+AtuRgwMyMOlAmoUkKFYHdGSehRWvSjnm8S3IJVBpecarrQp9fXHjAegw95i5SCydHhmrU1TcE0WFaCrARK4HCB+XUlFYjcwqNpzNvnILk8g7jydmHVJ+yCBQ7qVI="
  # AZURE_SUBSCRIPTION_ID
  - secure: "gf6F9BSpKgteRRd3AylAprGSpMEnTWV2TuTz/R0e4heM53nTra2I/ThwTnop+2cW/ubzRp4Nd/qg9+8WDJ0VjrglzrbRMmJESZOV6iXRr95yxkzrOaFUFTYFZmGrQT7kUDtoboYe7NazRKRrZEVHKU8+z8oA7fmrYeTon9mdNI9EsOrNwjqGJIrTRmWWPUQDF1iKqf6xyCxYNddfYkXOk94T/NyHZ2Wa3AuFOHonYp3ntZYEEX1fQjl71uABGvtuAm258sm3sNIYZfZr0L7c4MJ9uLZ7QcrG2O2rmfP027BXHa3a/A5wmEVjf1pfaJM26Bi6gdIqVMpledAvC9NynjgW3w6/jEUBpPw7t65fm6hDAmVFo4o44HVhIolSwaQc2GBI2MMNoIyEdoL9nj7Aaj+XP2qG6edbEwUXBOD1EBEVdA54I+S8aloWxVNrKEFwCaDjCm5en7a97u6//FizcUhNG5iVj8hrLxQ0gbAMQiKpSpKgLIdRhvW5LQn5qz+hDmyy6OKEMc6TLUtb5k3Nk9KKYsaeOyFL0C9Nle4m7YQyDFZqKZj1dV8jG0deJsVR2HYKBNa8xVEtGPfLWYF0Gl25mnO3Ma7b4rcTTZy5u9HR+ZAPrTdzNsB2rdK6xdCAMeGYQwnQmmQymrnLZTrxbYvYBlF2irMBluq7Sv//Nis="
  # AZURE_CLIENT_ID
  - secure: "u5mUDPSRade3J0YFTmPUiayWb985s4B3OqdQB0phcRKijhIH3956VcQWbCDxFvniM8bo4+ugXLIusjwt3LPUM91fyyVpb/Xj/I/L/EHRx9AKot4eDjnA1hOyX8MFr1Ka/pmIcx20LFM5eFSbS4JuPjMJwkQFw2c2fz4drorLNJ2uQ1tm0NesYtLuk0uUAKSZRfkHnTICaWHQkbwXYy0uZF11610waoAjK4YNMlULG+bosHjPH+5Ruxbpq+8Re7rf5pKcgNqQ4oEDO9ed8L8OU9/GiYf8whH/KL3q8vR2b9nqZ55bByApitKExXWl7ZUv9xG5iU+16yhbEUB2Q/Y5a01YqPQQdSuevRBPT7QYYr5AL7zeOtCXKgtgz39AJwncdt/zIbgWd6iu2w7dVoxBxGPwyPTGdRTxD0Q3alr4ETWvq17I0nadJVRt/TIlzZjDgf7brvJ9QcqqT84/tp3BjbIeUBgq8g8BnBBY5T6F/d2d9cayT8wfUZJxWCB7CHvsb3OA1S81H/rSDrdy0B4P5abRQU8s83pz/mYbn2EtdkPfVOQ4nkxTzQWbGsLjR2L/CW0BNlM3Mhv/09rBGB7SxnX4PYG65j2sWzz+b80lbCh9y7upFroYjBOIcSCJtWwKc8wT6rpACXoXLf8zeUEZuZevny1Wh1Fz7rgZvI1QWGY="
  # AZURE_CLIENT_SECRET
  - secure: "jDQp5Gd85NtX7vXsDnor/YQDofzYEQJH/YOWh/Hvg0iqrM0r1jSVpwCmkZyLOs0WpZGYEwj2poKPzSW9UVqOyPEcBxPcAGtwwWXwkNBmpEVshwQXzXDnFDIt40Mj/FQZduZYR2QtMCTKa/MqkRXlYBnAp5Mo5BUmds6/H5zHgAbXTP1aEgsOD8J9rbksOZQjHyTOM7WZLy54P8d7HuHIUQhNhktLLGB905DeWyIVlHLN7dUs7wKaVobRgK4oDDPY+9GdCNzOYdzFRSf8lmsZq6PLhtvoKxMtkYMIsiM3x0iCUM0VomX4CjLLZdhXYxNRKk7atxvEPy5KII1j7rR3AkCF/w0oC1oKC5q8E5T5W3vzSxloll/Vy32U88pTqjQ53lbtipaFrqqRzvtFBlDE4sGuAdHtugDsARlpwc2vaz1p93YPsc8oECJbf3I+pq8AwvNsYU+kJF/XLgu/TMAppOI59xU4rHa35bhKGHTtxc6QASagroHpHHlUexwvDI35zJmIR6lPOC5GpTn7MdylcgJsrROVQa29G0QV5BIJ7ZVL7+JAJ8WZmBHMvZbXy/8ucUKj8R7witF43GXNwlBjI+y1GKd8d2IVOz0gv7iYhsNUMsbx9igfB4E4MrFeOzbmOqKMqxMBqx+3K9ACHOcLHSJxWxRjB3po0UJmK5iWJyg="
  # AZURE_TENANT_ID
  - secure: "Og9zLaFIs25vaKB14caf9bnNQFRxCBPl7yHJcxTkZe8SL0V38V2svD9lYJyMQqZw3wqKM8dqrr/7G3pDpZJD33lqcmZuIojsyWdZJmsgLAbA//i9h4t5Ke4Fw4teDtnNO8qAUG+y0jbHMZ7y/921aB05VbR3WdysIVMKIYqaBJvlt7D5Mjs4QGulatrrUdmT6G544GQcIX8c400MEphkeOPI4S4h1pqXNWdQwzlBI+LSbQJeGsy6X0YelWtFJ1+d285N+XWBIid/Ga2Jn4QDEEuHfaU8XeDRCugOaxD1dj9aywI6RBjiywNjsmst5k5lR3/B7GelyPe/7TFUesi2nHbZ8OgUb2jVZ2Q1jyvFmbAHwBpaFUxF5caWhXopuwhnklQ779YwXyD44ssChwPgR4qx2lbPEfEZHNzZQx6fHPFc5UQmZBDClwXQVMOcyCcPO+SbacGBxWMEg5o+mIwXjehkGj9b12qaKs07/Y3T8X8JM4oVtqd1XKMfpDDBnu/7b/d8GbaBpVvwRqDVZGMiIdRRCzkAChuExakC8n5fOrpXHnSsilQdjKK8r4yOO9a1nFBHxHmuybFcHdYnACXMrgod80Dm9ozHNsGjLxzpXb7OSDVBH4mC+M7YWdEyEKbWQqXbM8FxTXLLyUaZ5r/tYt63YS/UlTuXogcJnrmkjWI="
  # AZURE_SERVER_USERNAME
  - secure: "AXTcA9e54ZEEfuYON9kj95giSkqzCY6NmQVMlof/UUx44GjIR3KqrNLZdYUDi9COfZnAfL9mHZT3tqFLo1lwMGfJ49JPnZ6OTpSoErrVyJLrvM34PpnHQFUfg5nDn4BlmnPiJyWEh6dpNeBqWTO+noLD4MiDQWWVY2hBtbqizKUQP6XsREXVJWGrM2MM5WemDw96F5qOCBjtGRqygqtbF91560lbQN2VIwURHoo/Ou0b4yNA7UIWCMC3rNAs6fYRodo0mGX1xijUxhJIxcbP4TioBUcwcNvEw+TDHMU8JnjvVFHAcPMeJpJV5IrzHGKBHwKcTiJxayA1Q9+wCUEc9gV1JRtetYbC7SwZILEYjPmVMaj8SDi8mgMwqb8vvG83UDx656Oo4kzx7hNvWWgndqugVAmfA9g3OrLQDo3fEOwarXqa1SdLorCwFL7ldz1djud4tRhcBxSa/0lORxdNUdkiSRwxRtZQ5fmvRYpWgoI9/MyAS+608kxYymyN+/iFxg4Un9Fk3bswmGiYpgLnoD5j0PLhJNvjm6J6eYjK7vQgL3L2FfbMaHuclV2B43LqisbjuwA909xEW8D1+I4ZJRBM3whEBUFJdfbczYKstPcTGG+NZkeH0eT7uhOhqCha5m8Cp9ae1NTpm16jmG6pNuO/Y2yLzgpMYnC3geKTjPc="
  # AZURE_SERVER_PASSWORD
  - secure: "NfwLOUyrw1jz/1AwyOj14vHXawMegDWBuwk3UCURaXW8eAL8JJkbYM2C2tNcQSFqbSodh/e9v2QqDx5LBPtaZAPLdIy2suwuAaceXioFJEgqEvNmZWTTdTP3p/I8w9PB9oEpbkxLt6WqsQk96CxZoWTKbm0xX/+vCoLaIEy5y+z4+qwFHvp0D8BB7a9ZCu4AZPzNMS2e95hNJ940teN4yvSQB2BHXgS/bu7Vwa1l4RgORXmq25jTRTNTCfgS9R0oRzCHGxtUq5BZss3BxVoIpzhx/K75z6Ui49WwFYeQwMB63XJty2QCTz7VuMy2ZaAxKS7aNmmgo1s+Pfvn2zbYC04l62tqauxf+X+q/ciaNw5UpOzW3rcR3ittnROwm6tAjuD46IqPT6FODAfm8+u5z0Aiuy4Er7CeiUYKjLejGJ0vMNi6HB7wkQIZkQYs7KPFscjGgZGJBEb88Qn7XbcJ76HCM2XaqPkhNBd4+Ur+zyNcMn9PvgsBCrGg+NBk5eRE8JBOBOu/b+ONKHvjQYhR3CReqlibf7li3fbPxEnG7NHsEnL4lwFL6qyFI1dBYTLwpsuouLz2do+k8x9L/CmbjSetUsohx3pORDHmkUag2T5IWkOIiwk5aNk9WonN096YK1IaKvvKh7pac67aHCHkmghVeSVJLFiFNCodPzinKlU="
  # AZURE_KUBE_USERNAME
  - secure: "pTU0a4orfCETw08wApxNbWKg5j+OVETIFmzR2yUWPp9d3w6v46vZzGixew3QpUVXdZtX8rLFc9s7H0Q3tN41qjQ1i8iaRLOYVuJ41Xz2sDpYFG77jCNxO5DwneuhbKH64A0XzK1tfFBNM3GybzX0a+0AccBFetoXp8gHF/iRNiUAT1IaJ7Aw28F3a9jiiGMK4CG0kTao05EUo60UQEB6gR00C1F6LWlVoV2V3MHjdU+Z87kj8SRwF/8oBPAW9skxVUNh7BkLUGEcicu83GkQKvVQQiNgSX0YCUt8+qiYtmgXMGSrfUfGrcVPwyJ/jUN6yp1S1DqWOc5tSi3UPUhesANN4PecVD36EZ5+KYXh9pqMT+zuNcLMlEjNWGhg+yXw4ZEOadl4I0lnyQ0ReqfuDwTQDhF4JnrC1WzCcOPJ5Z9dct4NhbTssuUxcxySZJekhv48Xo/iNLGEw/y/kIWu0f0wCpAC7Y/WMK3f7zMjzMv7ZeDSVTD54tLIn0cAhDf5qOCLd3JxX/hdlQ/2Q+1kl+Hu4SlIyudRQLFwdgcvNl+wm3IX1VISGH1ECnyNkzR1foHFxawMtKDDsGrRS98KvyrumeEjneTEmsO5HKIRSjCeXCfDnHqU8W0R6R3ullvNNuh61CvQojmKrgC5ANP6mjb6f90/X0pan+nBYTLTGkw="
  # AZURE_KUBE_SSH_PUBKEY
  - secure: "PXo9Shp5wGKNlSHSXInfc6ubuxXoG8C/ZW57C47rFxdFJPP+7kxkpdBAUEEFyvkHuMNJzqTxuNAcfkXdTMjOAVZvtftzR+i1S5nlGftvI47V5SoOrir5k/SI+7vibSD1HC5/+IyYpeS6CVne0xlaVg5+C8Ee11LUYnUSQplVe8fkiXsvZWd1tp9pbe18ue6xFUT/UbusyC0wswNsFcXwQM5+VCtqQAK4WpaWp3LgMh1JHoHNRCdx+cBSkXiyroO0nRi8ImN+JxC8NhNBz06dcqCUxaofkEkDgGLDvpy0JdCYI+F4ZdsoF1Vwhso01BpUxdvdvR+C3zjDKIrnwz5mPYY2UBta+4TNR5WaPYa76T6OgbhswhPTacs9GUxrUr/eysgD6OlzWHt0zGRXLJ4h7DCslU18tKqQZGncFVXWyAS7/nocmT28zSzg+SFO+O5WUUTK4odNSkVGeEaAR+7K5Sy3bXgv2+6HjIea4pWIoRdm98kzlQvIynoHnzuVjdlrgfC1eFBKpCTpuF0f2zCDigL77qPWtzN3o5LKAEU7vvN1IffxGRpDaiSTdMpERiB0PD4baHaFL1I8SFAvT4W50Qj8WRmTfGmlV9BZOglIQRRjlF7zYfjbuHANbDC/r4BUTLDimm6jiFY7CCX/MwwZc9ILjQu/iYrTmyd/QGXguTM="

  - TF_VAR_azure_subscription_id=$AZURE_SUBSCRIPTION_ID
  - TF_VAR_azure_client_id=$AZURE_CLIENT_ID
  - TF_VAR_azure_client_secret=$AZURE_CLIENT_SECRET
  - TF_VAR_azure_tenant_id=$AZURE_TENANT_ID

  - TF_VAR_azure_storage_account_name=$AZURE_STORAGE_ACCOUNT_NAME
  - TF_VAR_azure_container_name=$AZURE_CONTAINER_NAME

  - TF_VAR_azure_staging_global_state_key=$AZURE_STAGE_GLOBAL_STATE_KEY
  - TF_VAR_azure_staging_network_state_key=$AZURE_STAGE_NETWORK_STATE_KEY
  - TF_VAR_azure_staging_apps_state_key=$AZURE_STAGE_APPS_STATE_KEY
  - TF_VAR_azure_staging_registry_state_key=$AZURE_STAGE_REGISTRY_STATE_KEY

  - TF_VAR_azure_resource_group_name=$AZURE_RESOURCE_GROUP_NAME
  - TF_VAR_azure_storage_access_key=$AZURE_STORAGE_ACCESS_KEY
  - TF_VAR_azure_petshop_server_username=$AZURE_SERVER_USERNAME
  - TF_VAR_azure_petshop_server_password=$AZURE_SERVER_PASSWORD
  - TF_VAR_azure_kube_ssh_pubkey=$AZURE_KUBE_SSH_PUBKEY
  - TF_VAR_azure_kube_username=$AZURE_KUBE_USERNAME

before_install:
- chmod +x scripts/install_dependencies.sh
- chmod +x scripts/validate_plan.sh
- chmod +x scripts/deploy.sh
- make install

script:
- make validate


deploy:
- provider: script
  skip_cleanup: true
  script: make deploy
  on:
    repo: 
    branch: master
